
Mission_Enable = {
    1: "mission/mall_intro",
    2: "mission/lee_computers",
    3: "mission/lee_login",
    4: "mission/marina_demolish",
    5: "mission/marina_cars",
    6: "mission/marina_gps",
    7: "mission/mansion_pool",
    8: "mission/lee_safe",
    9: "mission/lee_tower",
    10: "mission/mansion_art",
    11: "mission/marina_tools",
    12: "mission/marina_art_back",
    13: "mission/mall_foodcourt",
    14: "mission/mansion_fraud",
    15: "mission/caveisland_computers",
    16: "mission/mansion_race",
    17: "mission/mansion_safe",
    18: "mission/lee_powerplant",
    19: "mission/caveisland_propane",
    20: "mission/caveisland_dishes",
    21: "mission/lee_flooding",
    22: "mission/frustrum_chase",
    23: "mission/factory_espionage",
    24: "mission/caveisland_ingredients",
    25: "mission/frustrum_tornado",
    26: "mission/mall_shipping",
    27: "mission/carib_alarm",
    28: "mission/carib_barrels",
    29: "mission/carib_destroy",
    30: "mission/carib_yacht",
    31: "mission/frustrum_vehicle",
    32: "mission/mall_decorations",
    33: "mission/factory_tools",
    34: "mission/mall_radiolink",
    35: "mission/frustrum_pawnshop",
    36: "mission/factory_robot",
    37: "mission/lee_woonderland",
    38: "mission/factory_explosive",
    39: "mission/caveisland_roboclear",
    40: "mission/cullington_bomb",
}

Tool_Enable = {
    41: "tool/sledge/enabled",
    42: "tool/spraycan/enabled",
    43: "tool/extinguisher/enabled",
    51: "tool/blowtorch/enabled",
    52: "tool/shotgun/enabled",
    53: "tool/plank/enabled",
    54: "tool/pipebomb/enabled",
    55: "tool/gun/enabled",
    56: "tool/bomb/enabled",
    57: "tool/rocket/enabled",
    58: "tool/booster/enabled",
    59: "tool/leafblower/enabled",
    60: "tool/wire/enabled",
    61: "tool/turbo/enabled",
    62: "tool/explosive/enabled",
    63: "tool/rifle/enabled",
    64: "tool/steroid/enabled",
}

Tool_Items = {
    71: ["tool/blowtorch/ammo", 10, 20],
    81: ["tool/shotgun/ammo", 12, 12],
    82: ["tool/shotgun/range", 20, 20],
    83: ["tool/shotgun/damage", 1, 3],
    91: ["tool/plank/ammo", 8, 8],
    92: ["tool/plank/width", 1, 3],
    93: ["tool/plank/length", 8, 40],
    101: ["tool/pipebomb/ammo", 6, 6],
    102: ["tool/pipebomb/damage", 1, 2],
    111: ["tool/gun/ammo", 6, 6],
    112: ["tool/gun/range", 20, 40],
    113: ["tool/gun/damage", 1, 1],
    121: ["tool/bomb/ammo", 6, 6],
    122: ["tool/bomb/damage", 1, 4],
    131: ["tool/rocket/ammo", 6, 6],
    132: ["tool/rocket/damage", 1, 3],
    141: ["tool/booster/ammo", 6, 6],
    142: ["tool/booster/power", 100, 200],
    143: ["tool/booster/time", 2, 4],
    151: ["tool/leafblower/power", 10, 20],
    161: ["tool/wire/ammo", 6, 6],
    162: ["tool/wire/stretch", 1, 3],
    171: ["tool/turbo/ammo", 6, 6],
    172: ["tool/turbo/power", 100, 200],
    181: ["tool/explosive/ammo", 4, 4],
    182: ["tool/explosive/damage", 1, 5],
    191: ["tool/rifle/ammo", 6, 6],
    201: ["tool/steroid/ammo", 1, 2],
    202: ["tool/steroid/time", 1, 4],
}

Cash_Value = {
    251: 20,
    252: 50,
    253: 100,
    254: 250,
    255: 500,
    256: 750,
    257: 1000,
    258: 3000
}
